mbp:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: trendmarketv2-analytics
      dataset: mbp
      threads: 4
      timeout_seconds: 300
      keyfile_json: "{{ env_var('DBT_BIGQUERY_SERVICE_ACCOUNT') }}"
