[package]
name = "trendmarketv2"
version = "0.1.0"
edition = "2021"

[lib]
name = "trendmarketv2"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "dec_benches"
harness = false
