name: ce_dbt
version: 1.0.0
profile: ce_profile
model-paths: ["models"]
test-paths: ['tests', 'models/tests']
seed-paths: ["seeds"]
models:
  ce_dbt:
    +materialized: view
    staging:
      +schema: stg
    marts:
      +schema: marts
seeds:
  ce_dbt:
    +schema: seed_data
