groups:
  - name: mbp_s5_oracles
    interval: 30s
    rules:
      - record: mbp:oracle:staleness_p95_ms
        expr: quantile_over_time(0.95, mbp_oracle_staleness_ms{env="prod"}[5m])
      - record: mbp:oracle:divergence_p95
        expr: quantile_over_time(0.95, mbp_oracle_diverg_pct{env="prod"}[5m])
      - record: mbp:oracle:quorum_ratio
        expr: sum(mbp_oracle_quorum_ok{env="prod"}) / sum(mbp_oracle_quorum_total{env="prod"})
      - record: mbp:oracle:failover_time_p95_s
        expr: quantile_over_time(0.95, mbp_oracle_failover_time_s{env="prod"}[15m])
  - name: mbp_s5_fees
    interval: 30s
    rules:
      - record: mbp:fee:delta_pct_5m
        expr: max_over_time(mbp_fee_delta_pct{env="prod"}[5m])
      - record: mbp:fee:in_bounds
        expr: avg_over_time(mbp_fee_in_bounds{env="prod"}[5m])
      - record: mbp:fee:cooldown_hits
        expr: increase(mbp_fee_cooldown_trigger_total{env="prod"}[5m])
  - name: mbp_s5_moderation
    interval: 30s
    rules:
      - record: mbp:moderation:pauses_total
        expr: increase(mbp_moderation_pause_total{env="prod"}[30m])
      - record: mbp:moderation:appeals_open
        expr: avg_over_time(mbp_moderation_appeals_open{env="prod"}[5m])
      - record: mbp:moderation:mttd_minutes
        expr: avg_over_time(mbp_moderation_mttd_seconds{env="prod"}[1h]) / 60
  - name: mbp_s5_simulation
    interval: 1m
    rules:
      - record: mbp:simulation:ttpv_p95_ms
        expr: quantile_over_time(0.95, mbp_simulation_ttpv_ms{env="prod"}[1h])
      - record: mbp:simulation:runs_total
        expr: increase(mbp_simulation_runs_total{env="prod"}[1h])
      - record: mbp:simulation:success_ratio
        expr: sum(increase(mbp_simulation_runs_success_total{env="prod"}[1h])) / sum(increase(mbp_simulation_runs_total{env="prod"}[1h]))
  - name: mbp_s5_auto_resolution
    interval: 1m
    rules:
      - record: mbp:auto_resolve:latency_p50_ms
        expr: histogram_quantile(0.5, sum(rate(mbp_auto_resolve_latency_ms_bucket{env="prod"}[15m])) by (le))
      - record: mbp:auto_resolve:latency_p95_ms
        expr: histogram_quantile(0.95, sum(rate(mbp_auto_resolve_latency_ms_bucket{env="prod"}[15m])) by (le))
      - record: mbp:auto_resolve:success_ratio
        expr: sum(increase(mbp_auto_resolve_attempts_total{env="prod",mode="auto",status="success"}[1h])) / sum(increase(mbp_auto_resolve_attempts_total{env="prod",mode="auto"}[1h]))
      - record: mbp:auto_resolve:backlog
        expr: max_over_time(mbp_auto_resolve_backlog{env="prod"}[15m])
      - alert: AutoResolveLatencyP95High
        expr: mbp:auto_resolve:latency_p95_ms > 7200000
        for: 30m
        labels:
          severity: warning
          team: plat
        annotations:
          summary: "Auto-resolution p95 latency exceeded 2h"
          runbook: docs/runbooks/dec_slo.md
      - alert: AutoResolveSuccessLow
        expr: mbp:auto_resolve:success_ratio < 0.9
        for: 30m
        labels:
          severity: warning
          team: plat
        annotations:
          summary: "Auto-resolution success ratio below 90%"
          runbook: docs/runbooks/dec_slo.md
      - alert: AutoResolveBacklogGrowing
        expr: mbp:auto_resolve:backlog > 10
        for: 30m
        labels:
          severity: warning
          team: plat
        annotations:
          summary: "Auto-resolution backlog above 10 pending items"
          runbook: docs/runbooks/dec_slo.md
    interval: 30s
    rules:
      - record: mbp:auto_resolve:latency_p95_ms
        expr: histogram_quantile(0.95, sum(rate(mbp_auto_resolve_eval_duration_seconds_bucket{env="prod"}[5m])) by (le)) * 1000
      - record: mbp:auto_resolve:success_ratio
        expr: sum(increase(mbp_auto_resolve_success_total{env="prod"}[30m])) / clamp_min(sum(increase(mbp_auto_resolve_decisions_total{env="prod"}[30m])), 1)
      - record: mbp:auto_resolve:backlog_max
        expr: max_over_time(mbp_auto_resolve_backlog{truth_source="__total__", env="prod"}[15m])

