name: trendmarketv2_analytics
version: 1.0.0
config-version: 2
profile: trendmarketv2_bq

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  +materialized: view
