title = "CRD-8 PII Rules"


[[rules]]
id = "cpf-br"
description = "CPF (Brasil)"
regex = '''\b\d{3}[\.-]?\d{3}[\.-]?\d{3}[\-]?\d{2}\b'''
entropy = 0.0


[[rules]]
id = "email-generic"
description = "Email genérico"
regex = '''[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'''


[[rules]]
id = "cc-pan"
description = "Provável cartão (PAN)"
regex = '''\b(?:\d[ -]*?){13,19}\b'''


[allowlist]
paths = [".gitignore", "LICENSE", "README.md"]
