# .github/workflows/_crd-orr.yml
name: _CRD ORR (Reusable)
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
      run_bundle:
        type: boolean
        required: false
        default: true
      profile:
        type: string
        required: false
        default: fast
      environment:
        type: string
        required: false
        default: dev
      epic_path:
        type: string
        required: false
        default: docs/obs/CRD-8-epic.md
      agents_md:
        type: string
        required: false
        default: AGENTS.md
permissions:
  contents: read
jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ORR
        shell: bash
        env:
          RUN_BUNDLE: ${{ inputs.run_bundle && '1' || '0' }}
          PROFILE: ${{ inputs.profile }}
          TARGET_ENV: ${{ inputs.environment }}
          EPIC_PATH: ${{ inputs.epic_path }}
          AGENTS_MD: ${{ inputs.agents_md }}
        run: |
          set -euo pipefail
          scripts/orr_env_probe.sh "$@"
          scripts/orr_t1_run.sh "$@"
          python3 scripts/orr_t2_parse_unit.py "$@"
          scripts/orr_t3_props_run.sh "$@"
          scripts/orr_t4_goldens_run.sh "$@"
          scripts/orr_t5_bench_run.sh "$@"
          python3 scripts/orr_t5_collect_criterion.py "$@"
          scripts/orr_t6_metrics_run.sh "$@"
          scripts/orr_t7_ci_prep.sh "$@"
          scripts/orr_t7_collect_ci.sh "$@"
          if [ "${RUN_BUNDLE}" = "1" ]; then
            scripts/orr_t8_bundle.sh "$@"
          fi
