# .github/workflows/_crd-orr.yml
name: _CRD ORR (Reusable)
on:
  workflow_call:
    inputs:
      ref: { type: string, required: false }
      run_bundle: { type: boolean, required: false, default: true }
      profile: { type: string, required: false, default: fast }
      environment: { type: string, required: false, default: dev }
      epic_path: { type: string, required: false, default: docs/obs/CRD-8-epic.md }
      agents_md: { type: string, required: false, default: AGENTS.md }
      project_dir: { type: string, required: false, default: . }
      scripts_dir: { type: string, required: false, default: "" }
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: Locate scripts dir
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          base="${{ inputs.project_dir }}"
          [ -d "$base" ] || { echo "::error::project_dir não existe: $base"; exit 1; }
          if [ -n "${{ inputs.scripts_dir }}" ] && [ -f "$base/${{ inputs.scripts_dir }}/orr_env_probe.sh" ]; then
            S="$base/${{ inputs.scripts_dir }}"
          else
            cand="$(find "$base" -type f -name 'orr_env_probe.sh' -print -quit || true)"
            [ -n "$cand" ] || { echo "::error::orr_env_probe.sh não encontrado sob $base. Ajuste inputs.project_dir/scripts_dir."; exit 1; }
            S="$(dirname "$cand")"
          fi
          D="$(cd "$S/.." && pwd)"
          echo "scripts=$S" >> "$GITHUB_OUTPUT"
          echo "dir=$D" >> "$GITHUB_OUTPUT"

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Preflight
        shell: bash
        working-directory: ${{ steps.locate.outputs.dir }}
        run: |
          set -euo pipefail
          S="${{ steps.locate.outputs.scripts }}"
          for f in orr_env_probe.sh orr_t1_run.sh orr_t3_props_run.sh orr_t4_goldens_run.sh orr_t5_bench_run.sh orr_t6_metrics_run.sh orr_t7_ci_prep.sh orr_t7_collect_ci.sh; do
            [ -x "$S/$f" ] || { echo "::error file=$S/$f::missing or not executable"; exit 1; }
          done
          [ -f "$S/orr_t2_parse_unit.py" ] || [ -f "$S/../scripts/orr_t2_parse_unit.py" ] || { echo "::error file=orr_t2_parse_unit.py::missing"; exit 1; }
          if [ "${{ inputs.run_bundle && '1' || '0' }}" != "0" ]; then
            [ -x "$S/orr_t8_bundle.sh" ] || { echo "::error file=$S/orr_t8_bundle.sh::missing"; exit 1; }
          fi

      - name: Run ORR
        shell: bash
        working-directory: ${{ steps.locate.outputs.dir }}
        env:
          RUN_BUNDLE: ${{ inputs.run_bundle && '1' || '0' }}
          PROFILE: ${{ inputs.profile }}
          TARGET_ENV: ${{ inputs.environment }}
          EPIC_PATH: ${{ inputs.epic_path }}
          AGENTS_MD: ${{ inputs.agents_md }}
        run: |
          set -euo pipefail
          S="${{ steps.locate.outputs.scripts }}"
          "$S/orr_env_probe.sh" "$@"
          "$S/orr_t1_run.sh" "$@"
          if [ -f "$S/orr_t2_parse_unit.py" ]; then python3 "$S/orr_t2_parse_unit.py" "$@"; else python3 "scripts/orr_t2_parse_unit.py" "$@"; fi
          "$S/orr_t3_props_run.sh" "$@"
          "$S/orr_t4_goldens_run.sh" "$@"
          "$S/orr_t5_bench_run.sh" "$@"
          if [ -f "$S/orr_t5_collect_criterion.py" ]; then python3 "$S/orr_t5_collect_criterion.py" "$@"; else python3 "scripts/orr_t5_collect_criterion.py" "$@"; fi
          "$S/orr_t6_metrics_run.sh" "$@"
          "$S/orr_t7_ci_prep.sh" "$@"
          "$S/orr_t7_collect_ci.sh" "$@"
          if [ "${RUN_BUNDLE}" = "1" ]; then "$S/orr_t8_bundle.sh" "$@"; fi
