name: _CRD ORR (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
      run_bundle:
        type: boolean
        required: false
        default: true

permissions:
  contents: read

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Semeadura do ORR (se ausente)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f scripts/orr_all.sh ]; then
            mkdir -p scripts
            printf '%s\n' \
'#!/usr/bin/env bash' \
'set -euo pipefail' \
'' \
'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"' \
'cd "$ROOT_DIR"' \
'' \
'scripts/orr_env_probe.sh "$@"' \
'scripts/orr_t1_run.sh "$@"' \
'python3 scripts/orr_t2_parse_unit.py "$@"' \
'scripts/orr_t3_props_run.sh "$@"' \
'scripts/orr_t4_goldens_run.sh "$@"' \
'scripts/orr_t5_bench_run.sh "$@"' \
'python3 scripts/orr_t5_collect_criterion.py "$@"' \
'scripts/orr_t6_metrics_run.sh "$@"' \
'scripts/orr_t7_ci_prep.sh "$@"' \
'scripts/orr_t7_collect_ci.sh "$@"' \
'if [ "${RUN_BUNDLE:-1}" = "1" ]; then' \
'  scripts/orr_t8_bundle.sh "$@"' \
'fi' \
> scripts/orr_all.sh
            chmod +x scripts/orr_all.sh
          fi

      - name: Executar ORR completo
        shell: bash
        env:
          RUN_BUNDLE: ${{ inputs.run_bundle && '1' || '0' }}
        run: |
          set -euo pipefail
          for f in scripts/orr_env_probe.sh scripts/orr_t1_run.sh scripts/orr_t3_props_run.sh scripts/orr_t4_goldens_run.sh scripts/orr_t5_bench_run.sh scripts/orr_t6_metrics_run.sh scripts/orr_t7_ci_prep.sh scripts/orr_t7_collect_ci.sh; do
            [ -x "$f" ] || { echo "::error file=$f::arquivo ausente ou sem execução"; exit 1; }
          done
          [ -f scripts/orr_t2_parse_unit.py ] || { echo "::error file=scripts/orr_t2_parse_unit.py::arquivo ausente"; exit 1; }
          [ "${RUN_BUNDLE}" = "0" ] || [ -x scripts/orr_t8_bundle.sh ] || { echo "::error file=scripts/orr_t8_bundle.sh::arquivo ausente"; exit 1; }
          ./scripts/orr_all.sh
