name: _CRD ORR (Reusable)
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
      run_bundle:
        type: boolean
        required: false
        default: true
permissions:
  contents: read
jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3_11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ORR
        shell: bash
        env:
          RUN_BUNDLE: ${{ inputs.run_bundle }}
        run: |
          set -euo pipefail
          scripts/orr_env_probe.sh "$@"
          scripts/orr_t1_run.sh "$@"
          python3 scripts/orr_t2_parse_unit.py "$@"
          scripts/orr_t3_props_run.sh "$@"
          scripts/orr_t4_goldens_run.sh "$@"
          scripts/orr_t5_bench_run.sh "$@"
          python3 scripts/orr_t5_collect_criterion.py "$@"
          scripts/orr_t6_metrics_run.sh "$@"
          scripts/orr_t7_ci_prep.sh "$@"
          scripts/orr_t7_collect_ci.sh "$@"
          if [ "${RUN_BUNDLE}" = "true" ]; then
            scripts/orr_t8_bundle.sh "$@"
          fi
