# .github/workflows/_s4-orr.yml
name: "S4 ORR Reusable"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
      run_microbench:
        type: boolean
        required: false
        default: false
      run_tla:
        type: boolean
        required: false
        default: false

concurrency:
  group: s4-orr-${{ inputs.ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  orr:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo inputs
        run: |
          echo "ref=${{ inputs.ref }}"
          echo "run_microbench=${{ inputs.run_microbench }}"
          echo "run_tla=${{ inputs.run_tla }}"
