name: _s4-orr

on:
  workflow_call:
    inputs:
      ref:
        description: Optional ref to run against
        required: false
        type: string
      run_microbench:
        description: Enable microbench gate
        required: false
        type: boolean
        default: false
      run_tla:
        description: Enable TLA verification
        required: false
        type: boolean
        default: false

concurrency:
  group: s4-orr-${{ inputs.ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  orr:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    env:
      PROM_URL: http://127.0.0.1:9090
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Harden runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Python deps (dbt only)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core==1.6.4" "dbt-bigquery==1.6.4" "requests==2.31.0"

      - name: Python env audit
        run: |
          mkdir -p out/pip-audit
          pip --version > out/pip-audit/pip-version.txt
          pip freeze | sort > out/pip-audit/pip-freeze.txt

      - name: Upload pip audit
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit
          path: out/pip-audit

      - name: Install security tools
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz | tar xz
          sudo install -m 0755 gitleaks /usr/local/bin/gitleaks
          rm -f gitleaks LICENSE README.md || true

          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.tar.gz | tar xz
          sudo install -m 0755 trivy /usr/local/bin/trivy
          rm -f trivy LICENSE README.md || true

          curl -sSLo semgrep https://github.com/semgrep/semgrep/releases/download/v1.80.0/semgrep-linux-amd64
          curl -sSLo semgrep.sha256 https://github.com/semgrep/semgrep/releases/download/v1.80.0/semgrep-linux-amd64.sha256
          sha256sum -c semgrep.sha256
          sudo install -m 0755 semgrep /usr/local/bin/semgrep
          rm -f semgrep semgrep.sha256
          semgrep --version

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm deps
        run: npm ci --ignore-scripts

      - name: Resolve k6 digest
        id: k6
        run: |
          set -euo pipefail
          IMAGE=grafana/k6:0.52.0
          docker pull "$IMAGE" >/dev/null
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")
          echo "image=$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Run dbt build
        if: ${{ hashFiles('analytics/dbt/**') != '' }}
        run: dbt build --project-dir analytics/dbt --profiles-dir analytics/dbt/profiles

      - name: Generate dbt docs
        if: ${{ hashFiles('analytics/dbt/**') != '' }}
        run: dbt docs generate --project-dir analytics/dbt --profiles-dir analytics/dbt/profiles

      - name: Upload TLA report
        if: ${{ hashFiles('out/s4_orr/tla_report.txt') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: tla-report
          path: out/s4_orr/tla_report.txt
