# .github/workflows/crd-epic-exec.yml
name: CRD Epic - Exec
on:
  workflow_dispatch:
    inputs:
      profile:
        description: Perfil (fast | full)
        type: choice
        default: fast
        options: [fast, full]
      environment:
        description: Ambiente alvo (dev | staging)
        type: choice
        default: dev
        options: [dev, staging]
      epic_path:
        description: Caminho do arquivo do épico (MD)
        required: true
        default: docs/obs/CRD-8-epic.md
      agents_md:
        description: Caminho do AGENTS.md
        required: true
        default: AGENTS.md
      run_matrix:
        description: Executar matriz (fast/full × dev/staging)?
        type: boolean
        default: false
  issue_comment:
    types: [created]

permissions:
  contents: read
  actions: write
  checks: write

concurrency:
  group: exec-${{ github.ref }}
  cancel-in-progress: true

jobs:
  exec_single:
    if: ${{ (github.event_name == 'workflow_dispatch' && !fromJSON(inputs.run_matrix || 'false')) || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/crd exec')) }}
    uses: ./.github/workflows/_crd-orr.yml
    with:
      profile: ${{ github.event_name == 'issue_comment' && (contains(github.event.comment.body, 'full') && 'full' || 'fast') || inputs.profile }}
      environment: ${{ github.event_name == 'issue_comment' && (contains(github.event.comment.body, 'staging') && 'staging' || 'dev') || inputs.environment }}
      epic_path: ${{ inputs.epic_path }}
      agents_md: ${{ inputs.agents_md }}
      project_repo: gustavomhss/trendmarketv2
      project_ref: main
      project_dir: .

  exec_matrix:
    if: ${{ (github.event_name == 'workflow_dispatch' && fromJSON(inputs.run_matrix || 'false')) || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/crd matrix')) }}
    strategy:
      fail-fast: false
      matrix:
        profile: [fast, full]
        environment: [dev, staging]
    uses: ./.github/workflows/_crd-orr.yml
    with:
      profile: ${{ matrix.profile }}
      environment: ${{ matrix.environment }}
      epic_path: ${{ inputs.epic_path }}
      agents_md: ${{ inputs.agents_md }}
      project_repo: gustavomhss/trendmarketv2
      project_ref: main
      project_dir: .
