name: crd-epic-plan (stub)

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  noop:
    runs-on: ubuntu-22.04
    steps:
      - name: CRD Epic Plan stub
        shell: bash
        run: |
          echo "[stub] crd-epic-plan.yml — safe stub"
          echo "TODO: bring back real pipeline"
