# .github/workflows/s4-exec.yml
name: "S4 ORR Exec"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref opcional para checkout"
        required: false
        type: string
      run_microbench:
        description: "Executar microbench DEC"
        required: false
        type: boolean
        default: false
      run_tla:
        description: "Executar checagens TLA"
        required: false
        type: boolean
        default: false
      run_sut:
        description: Start SUT via docker-compose
        required: false
        type: boolean
        default: false
      bq_enable:
        description: "Habilitar rota BigQuery"
        required: false
        type: boolean
        default: false
      run_sim:
        description: "Executar harness de simulação S5"
        required: false
        type: boolean
        default: false
      run_dbt_ci:
        description: "Executar dbt-ci com DuckDB"
        required: false
        type: boolean
        default: false

jobs:
  call-orr:
    name: "Chamar workflow reutilizável"
    uses: ./.github/workflows/_s4-orr.yml
    with:
      ref: ${{ inputs.ref }}
      run_microbench: ${{ inputs.run_microbench }}
      run_tla: ${{ inputs.run_tla }}
      run_sut: ${{ inputs.run_sut }}
      bq_enable: ${{ inputs.bq_enable }}
      run_sim: ${{ inputs.run_sim }}
      run_dbt_ci: ${{ inputs.run_dbt_ci }}
    secrets: inherit

  aggregate-boss-final:
    name: "Aggregate Boss Final"
    runs-on: ubuntu-22.04
    needs: [call-orr]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar zips de estágio → out/boss
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out/boss
          found=false
          while IFS= read -r -d '' z; do
            cp -v "$z" out/boss/ || true
            found=true
          done < <(find . -type f -name 'boss-stage-*.zip' -print0 || true)
          ls -l out/boss || true
          if [ "$found" = false ]; then
            echo "[aggregate-boss] aviso: nenhum boss-stage-*.zip encontrado no workspace; ensure_schema fará rglob."
          fi

      - name: Aggregate reports (local)
        shell: bash
        env:
          BOSS_OUT_DIR: out/boss
          BOSS_STAGE_GLOB: boss-stage-*.zip
        run: |
          set -euo pipefail
          python -m scripts.boss_final.aggregate_reports_local
