# .github/workflows/s4-exec.yml
name: "S4 ORR Exec"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref opcional para checkout"
        required: false
        type: string
      run_microbench:
        description: "Executar microbench DEC"
        required: false
        type: boolean
        default: false
      run_tla:
        description: "Executar checagens TLA"
        required: false
        type: boolean
        default: false
      run_sut:
        description: Start SUT via docker-compose
        required: false
        type: boolean
        default: false
      bq_enable:
        description: "Habilitar rota BigQuery"
        required: false
        type: boolean
        default: false
      run_sim:
        description: "Executar harness de simulação S5"
        required: false
        type: boolean
        default: false
      run_dbt_ci:
        description: "Executar dbt-ci com DuckDB"
        required: false
        type: boolean
        default: false

jobs:
  call-orr:
    name: "Chamar workflow reutilizável"
    uses: ./.github/workflows/_s4-orr.yml
    with:
      ref: ${{ inputs.ref }}
      run_microbench: ${{ inputs.run_microbench }}
      run_tla: ${{ inputs.run_tla }}
      run_sut: ${{ fromJSON(github.event.inputs.run_sut || 'false') }}
      bq_enable: ${{ inputs.bq_enable }}
      run_sim: ${{ fromJSON(github.event.inputs.run_sim || 'false') }}
      run_dbt_ci: ${{ fromJSON(github.event.inputs.run_dbt_ci || 'false') }}
    secrets: inherit
