# .github/workflows/s4-exec.yml
name: "S4 ORR Exec"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref opcional para checkout"
        required: false
        type: string
      run_microbench:
        description: "Executar microbench DEC"
        required: false
        type: boolean
        default: false
      run_tla:
        description: "Executar checagens TLA"
        required: false
        type: boolean
        default: false
      run_security:
        description: "Executar varreduras de segurança"
        required: false
        type: boolean
        default: false
      security_fail_on_findings:
        description: "Falhar se houver findings de segurança"
        required: false
        type: boolean
        default: false

jobs:
  call-orr:
    name: "Chamar workflow reutilizável"
    uses: ./.github/workflows/_s4-orr.yml
    with:
      ref: ${{ github.event.inputs.ref }}
      run_microbench: ${{ fromJSON(github.event.inputs.run_microbench || 'false') }}
      run_tla: ${{ fromJSON(github.event.inputs.run_tla || 'false') }}
      run_security: ${{ fromJSON(github.event.inputs.run_security || 'false') }}
      security_fail_on_findings: ${{ fromJSON(github.event.inputs.security_fail_on_findings || 'false') }}
    secrets: inherit
