name: "Sprint 5 Validation"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Optional ref to validate"
        required: false
        type: string

jobs:
  sprint5-validate:
    name: "Sprint 5 validation suite"
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.lock

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install pytest 'dbt-duckdb~=1.8.0'

      - name: Configure dbt profile
        run: |
          set -euo pipefail
          mkdir -p ~/.dbt
          cp ops/dbt/profiles_duckdb.yml ~/.dbt/profiles.yml

      - name: Run Sprint 5 unit and integration tests
        run: |
          set -euo pipefail
          pytest tests/unit tests/integration

      - name: Run Sprint 5 simulations
        run: |
          set -euo pipefail
          make sim-all

      - name: Run Sprint 5 dbt pipeline
        run: |
          set -euo pipefail
          make dbt-ci

      - name: Package ORR evidence bundle
        run: |
          set -euo pipefail
          make orr-bundle

      - name: Upload Sprint 5 artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sprint5-validation-artifacts
          path: |
            out/**
            target/**
            logs/**
          if-no-files-found: warn
