# ⚠️ Relatório não encontrado. Veja GITHUB_STEP_SUMMARY para detalhes.
name: stub-valid-yaml
on: {workflow_dispatch: {}}
jobs:
  noop:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ok
      - name: fallback-message
        run: echo "⚠️ Relatório não encontrado. Veja GITHUB_STEP_SUMMARY para detalhes."
