name: Sanity — Actions Pins
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Resolve & Verify Pins
        shell: bash
        run: |
          set -euo pipefail
          python .github/scripts/verify_pins.py > .pins
          : > .summary || true
          FAIL=0
          while IFS=$'\t' read -r file action ref; do
            if ! [[ "$ref" =~ ^[0-9a-fA-F]{40}$ ]]; then echo "NO-SHA: $file $action@$ref" >> .summary; FAIL=1; continue; fi
            code=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/${action}/commits/${ref}")
            if [ "$code" != "200" ]; then echo "NO-COMMIT: $file $action@$ref ($code)" >> .summary; FAIL=1; fi
          done < .pins
          {
            echo "### Sanity Pins — $(date -u +%F)"
            if [ -s .summary ]; then echo; echo "**Issues:**"; sed -E 's/^/- /' .summary; else echo; echo "Tudo OK: todos os `uses` possuem SHA(40) válido."; fi
          } >> "$GITHUB_STEP_SUMMARY"
          exit $FAIL
