name: Sanity — Actions Pins
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '17 5 * * 1'
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Verify action pins and existence
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          python .github/scripts/verify_pins.py --report out/guard/s4/actions_pins_report.json
      - name: Upload pins report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sanity-actions-pins
          path: out/guard/s4/actions_pins_report.json
          if-no-files-found: error
          retention-days: 7
