name: semgrep

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: Optional ref to scan
        required: false
        type: string
      fail_on_findings:
        description: Fail the workflow when findings are detected
        required: false
        type: boolean
        default: false
    secrets:
      SEMGREP_APP_TOKEN:
        required: false

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Semgrep Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Run Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: ${{ !inputs.fail_on_findings }}
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        with:
          config: auto
          generateSarif: true
          publishSarif: true

      - name: Collect Semgrep artifacts
        if: ${{ always() }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out/security
          if [ -f semgrep.sarif ]; then
            cp semgrep.sarif out/security/semgrep.sarif
          fi
          if [ -f semgrep.json ]; then
            cp semgrep.json out/security/semgrep.json
          fi
          if [ -f semgrep.log ]; then
            cp semgrep.log out/security/semgrep.log
          fi

      - name: Upload Semgrep artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: semgrep-artifacts
          path: out/security/**
          if-no-files-found: warn

      - name: Record Semgrep outcome
        if: ${{ always() }}
        id: summary
        shell: bash
        run: |
          if [ "${{ steps.semgrep.outcome }}" = "failure" ]; then
            echo "exit_code=1" >> "$GITHUB_OUTPUT"
          else
            echo "exit_code=0" >> "$GITHUB_OUTPUT"
          fi

    outputs:
      exit_code: ${{ steps.summary.outputs.exit_code }}
